version: '3'

services:

  #  The Application
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
      - .:/var/www
    env_file: '.env.prod'
    environment:
      DB_CONNECTION: "mysql"
      DB_HOST: "127.0.0.1"
      DB_PORT: "8991"
      DB_DATABASE: "stemco_db"
      DB_USERNAME: "root"
      DB_PASSWORD: "finallyJDBC2017."
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  # The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
      - .:/var/www
    ports:
      - 8990:80
    depends_on:
      - app
      - database
    networks:
      - internal

  # The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=stemco_db"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - 8991:3306

volumes:
  dbdata:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28